--drop schema reimbursementschema;
--
--create schema reimbursementschema AUTHORIZATION postgres;
----- permissions -------
--GRANT ALL ON SCHEMA reimbursementschema TO postgres;
--
-- Drop table
--
-- DROP TABLE reimbursementschema.employee;
--
--CREATE TABLE reimbursementschema.employee (
--	employee_id serial NOT NULL,
--	first_name varchar(255) NOT NULL,
--	last_name varchar(255) NOT NULL,
--	username varchar(255) NOT NULL,
--	password varchar(255) not null,
--	"role" varchar(255) NOT null,
--	primary key (employee_id)
--);
--
--ALTER TABLE reimbursementschema.employee OWNER TO postgres;
--GRANT ALL ON TABLE reimbursementschema.employee TO postgres;
--
-- Drop table reimbursementschema.ticket;
--
-- DROP TABLE reimbursementschema.ticket;
--
--CREATE TABLE reimbursementschema.ticket (
--	ticket_id serial NOT NULL,
--	status varchar(255) NOT NULL,
--	note varchar(500) NOT NULL,
--	type varchar(255) NOT NULL,
--	amount double precision NOT NULL,
--	date_made date NOT NULL,
--	date_resolved date NOT NULL,
--	employee_id int NOT null,
--	primary key (ticket_id),
--	constraint fk_employee
--		foreign key(employee_id)
--			references "reimbursementschema".employee(employee_id)
--);
--
--
--ALTER TABLE reimbursementschema.employee OWNER TO postgres;
--GRANT ALL ON TABLE reimbursementschema.employee TO postgres;
--
--
--insert into reimbursementschema.employee (first_name, last_name, username, password, role)
--values ('Joe', 'Schmoe', 'username1', 'password', 'employee'),
--('Jane', 'Doe', 'username2', 'password', 'admin');
--
--insert into "reimbursementschema".ticket(status, note, type, amount, date_made, date_resolved, employee_id)
--values('pending', 'lunch with client', 'food', 50.00, Now(), Now(), 1),
--('pending', 'train ticket', 'travel', 60.00, Now(), Now(), 2);
--
--
select * reimbursementschema.employee;
